<div class="page-title">
    <h1><?php echo $this->__('My images') ?></h1>
</div>

<form action="<?php echo Mage::getUrl('inchoo_image/image/saveimage') ?>" method="post" id="new_image" enctype="multipart/form-data">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Upload new image') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="title" class="required"><em>*</em>Title</label> 
                    <div class="input-box">
                        <input id="title" class="input-box required-entry" type="text" name="title" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="uploaded_image" class="required"><em>*</em>Choose an image</label>
                    <input id="uploaded_image" class="required-entry" type="file" name="uploaded_image" />
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <button type="submit" title="<?php echo $this->__('Upload image') ?>" class="button"><span><span><?php echo $this->__('Upload image') ?></span></span></button>
    </div>
</form>
<a href="<?php echo Mage::getUrl('inchoo_image/image/index') ?>"> &laquo; Back </a>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('new_image', true);
//]]>
</script>
