<div class="page-title">
    <h1><?php echo $this->__('My images') ?></h1>
</div>

<div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Options') ?></h2>
        <button  title="<?php echo $this->__('Upload new image') ?>" class="button"><a style="text-decoration:none;" href="<?php echo Mage::getUrl('inchoo_image/image/new') ?>"> <span> <span><?php echo $this->__('Upload new image') ?></span></span> </a></button>
        <br /> <br />
        <button  title="<?php echo $this->__('View uploaded images') ?>" class="button"> <a style="text-decoration:none;" href="<?php echo Mage::getUrl('inchoo_image/image/view') ?>"><span> <span><?php echo $this->__('View uploaded images') ?></span></span></a></button>
</div>
