<?php 
    $images = $this->getImagesByUserId();
    $user_email = Mage::getSingleton('customer/session')->getCustomer()->getEmail();
    $image_folder = Mage::getBaseUrl('media') . DS . 'inchooimages' . DS .  $user_email;
?>
<div class="page-title">
    <h1><?php echo $this->__('My images') ?></h1>
</div>

<div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Uploaded images') ?></h2>
        <?php foreach ($images as $image): ?>
            <ul style="display:inline-block;list-style: none;">
                <li style="margin-right:20px;">
                    <img class="image" src="<?php echo $image_folder . DS . $image->getImageName(); ?>" width="100" height="100" />
                    <p class="image-label" style="text-align:center;font:bold 12px Segoe UI;"> <?php echo $image->getImageTitle(); ?> </p>
                </li>
            </ul>
        <?php endforeach; ?>
</div>
