<?php
$id = Mage::getSingleton('customer/session')->getCustomer()->getId();
$tickets = Mage::getModel('inchoo_support/ticket')->getCollection()->addFieldToFilter('user_id', $id);
?>
<form action="<?php echo Mage::getUrl('inchoo_support/ticket/create') ?>" method="post" id="support-validate">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Ticket Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="title" class="required"><em>*</em>Title</label>
                    <div class="input-box">
                        <input id="title" class="input-box required-entry" type="text" name="title" />
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="field">
                    <label for="ticket_body" class="required"><em>*</em>Text</label>
                    <div class="input-box">
                        <textarea id="ticket_body" class="textarea required-entry" name="ticket_body" rows="5"></textarea>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <button type="submit" title="<?php echo $this->__('Submit ticket') ?>" class="button"><span><span><?php echo $this->__('Submit ticket') ?></span></span></button>
    </div>
</form>
<br>
<table class="data-table"> 
    <tr>
        <td>Ticket Name</td>
        <td>Ticket Description</td>
        <td>Date Created</td>
        <td>Resolved</td>
        <td>View</td>
    </tr>
    <?php foreach ($tickets as $ticket): ?>
        <tr>
            <td><?php echo $ticket->getTitle(); ?></td>
            <td><?php echo $ticket->getDescription(); ?></td>
            <td><?php echo $ticket->getCreated();?></td>
            <?php if($ticket->getFlag()== 1):?>
            <td><?php echo $ticket->getResolved();?></td>
            <?php else:?>
            <td><?php echo $this->__('Not Resolved');?></td>
            <?php endif; ?>
            <td><a href="/support/ticket/view/id/<?php echo $ticket->getTicket_id(); ?>">View</a></td>
        <tr>
<?php endforeach; ?>
</table>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('support-validate', true);
//]]>
</script>
